export enum ResponseStatusEnum {
    SUCCESS = 'SUCCESS',

    USER_NOT_ACTIVATED = 'USER_NOT_ACTIVATED',

    AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',

    AUTHORIZATION_FAILED = 'AUTHORIZATION_FAILED',

    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',

    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',

    BAD_REQUEST = 'BAD_REQUEST'


}
